site_name: Preprocess Toolbox
theme:
  name: material
  highlightjs: true
nav:
  - Home: 'index.md'
  - 'commands.md'
  - 'usage.md'
  - GitHub: 'https://github.com/environmental-forecasting/preprocess-toolbox'
plugins:
  - search
  - mkdocstrings:
      handlers:
        python:
          options:
            docstring_style: sphinx
            heading_level: 3
markdown_extensions:
  - markdown_include.include:
      base_path: .
  - admonition

# Include extra CSS to make some style adjustments
extra_css:
  - stylesheets/readthedocs.css

# Include extra JS to setup Read the Docs addons integrations
extra_javascript:
  - javascripts/readthedocs.js
